apiVersion: v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    metadata:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: us.gcr.io/ticketing-dev-43016/client

---

apiVersion: 1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      ports: 3000
      targetPort: 3000